#
# Copyright (c) Siemens AG, 2014-2018
#
# Authors: J.Lauenstein
#
# This work is licensed under the terms of the GNU GPL, version 2.  See
# the COPYING file in the top-level directory.
#

env:
  matrix:
#    - TARGET=x86
#    - TARGET=i386
    - TARGET=arm
    - TARGET=arm64

language: c

compiler:
  - gcc

sudo: required
dist: trusty

# Remove bogus python installations from PATH,
# see https://github.com/travis-ci/travis-ci/issues/5326
before_install:
  - export PATH=$(echo $PATH | sed 's/\/opt\/python[^:]*//g')

install:
  # Install additional packages
  - sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu xenial main'
  - sudo apt-get update -qq 
  - sudo apt-get install -qq make
  - if [  -d ci/ipipe ]; then
        pushd ci;
        git clone --depth=50 --branch=ipipe-4.9.y https://github.com/jlauenstein/ipipe.git ipipe;
        popd;
    fi

cache:
  directories:
  - ci/ipipe

script:
  - ci/build_all.sh
